services:
  postgis:
    build:
      context: .
      args:
        SSL_CRT_FILEPATH: "${SSL_CRT_FILEPATH}"
        SSL_KEY_FILEPATH: "${SSL_KEY_FILEPATH}"
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
